#!/bin/bash

# Run /chapter on every mp3 listed in batch_chapters.txt, one fresh `claude -p` session per talk.
# Finished talks (blog page and <name>_blog_en.txt exist) are skipped, so the script can be
# stopped and re-run at any time. When Claude hits a usage limit, it waits and retries.
# After each talk the gallery (output/index.html, topics in gallery_topics.txt) is rebuilt.
#
# Usage: ./batch_chapters.sh [list_file]
#
# Settings (environment variables):
#   MODEL            claude model (default: claude-opus-5-5, the model the first chapters were made with)
#   EFFORT           claude effort level: low, medium, high, xhigh, max (default: low)
#   PERMISSION_MODE  claude permission mode (default: auto)
#   LIMIT_WAIT       seconds to wait after a usage limit before retrying (default: 1800)
#   MAX_FAILURES     other failures allowed per talk before skipping it (default: 2)
#   PUSH             1 = commit output/<name>/ and the gallery on the current branch and push after each talk (default: 1)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

LIST="${1:-batch_chapters.txt}"
MODEL="${MODEL:-claude-opus-5-5}"
EFFORT="${EFFORT:-low}"
PERMISSION_MODE="${PERMISSION_MODE:-auto}"
LIMIT_WAIT="${LIMIT_WAIT:-1800}"
MAX_FAILURES="${MAX_FAILURES:-2}"
PUSH="${PUSH:-1}"
LOG_DIR="tools/batch_logs"
NOTES="$LOG_DIR/REVIEW_NOTES.md"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $(date '+%H:%M') $1"; }
log_warn()  { echo -e "${YELLOW}[WAIT]${NC} $(date '+%H:%M') $1"; }
log_error() { echo -e "${RED}[FAIL]${NC} $(date '+%H:%M') $1" >&2; }

if [ ! -f "$LIST" ]; then
    log_error "List file not found: $LIST"
    exit 1
fi
mkdir -p "$LOG_DIR"

# Output name: file name without .mp3 and the trailing _<11-char video ID>
default_name() {
    local base
    base="$(basename "$1" .mp3)"
    if [[ "$base" =~ ^(.+)_[A-Za-z0-9_-]{11}$ ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        echo "$base"
    fi
}

# Finished = blog page plus the English blog text (only the current process writes that), so
# talks generated by the older single-chapter process are regenerated.
is_done() {
    [ -f "output/$1/blog/index.html" ] && [ -f "output/$1/$1_blog_en.txt" ]
}

is_usage_limit() {
    grep -qiE "usage limit|limit reached|rate limit|limit will reset|out of extra usage|429" "$1"
}

done_count=0
skipped=()

while read -r input name _; do
    [[ -z "$input" || "$input" == \#* ]] && continue
    name="${name:-$(default_name "$input")}"

    if is_done "$name"; then
        continue
    fi
    if [ ! -f "$input" ]; then
        log_error "$input: file not found, skipping"
        skipped+=("$name (file not found)")
        continue
    fi

    failures=0
    while true; do
        log_info "$name: running /chapter ($MODEL, effort $EFFORT)"
        log="$LOG_DIR/$name.log"
        claude -p "/chapter $input $name" --permission-mode "$PERMISSION_MODE" \
            --model "$MODEL" --effort "$EFFORT" \
            < /dev/null > "$log" 2>&1

        if is_done "$name"; then
            break
        fi
        if is_usage_limit "$log"; then
            log_warn "$name: usage limit reached, retrying in $((LIMIT_WAIT / 60)) min"
            sleep "$LIMIT_WAIT"
            continue
        fi
        failures=$((failures + 1))
        log_error "$name: no blog page produced (attempt $failures/$MAX_FAILURES), see $log"
        if [ "$failures" -ge "$MAX_FAILURES" ]; then
            skipped+=("$name (failed, see $log)")
            continue 2
        fi
    done

    { echo "## $name"; echo; cat "$log"; echo; } >> "$NOTES"

    python3 tools/template/gallery_page.py > /dev/null ||
        log_error "$name: gallery rebuild failed (output/index.html)"

    if [ "$PUSH" = "1" ]; then
        git add "output/$name" output/index.html output/assets &&
            git commit -q -m "Add chapter: $name" -- "output/$name" output/index.html output/assets &&
            git push -q ||
            log_error "$name: git commit/push failed, files are still in output/$name"
    fi
    done_count=$((done_count + 1))
    log_info "$name: done"
done < "$LIST"

echo
log_info "Finished: $done_count chapter(s) generated. Review notes: $NOTES"
if [ ${#skipped[@]} -gt 0 ]; then
    log_error "Skipped ${#skipped[@]}:"
    printf '  - %s\n' "${skipped[@]}" >&2
    exit 1
fi
